spring:
  application:
    name : sampleApp
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5435/app}
    username: ${JDBC_DATABASE_USERNAME:app}
    password: ${JDBC_DATABASE_PASSWORD:app}
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
#drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
sleuth:
  sampler:
    probability: 1 # report 100% of traces

logging:
  level:
#    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.appCompany.sampleApp: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url=true:
  api-docs:
    path: /api-docs