spring:
  application:
    name : sampleApp
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5435/app}
    username: ${JDBC_DATABASE_USERNAME:app}
    password: ${JDBC_DATABASE_PASSWORD:app}
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
sleuth:
  sampler:
    probability: 1 # report 100% of traces

#logging:
#  level:
#    ROOT: DEBUG
#    org.hibernate.SQL: DEBUG
#    com.appCompany.sampleApp: DEBUG

feign:
  hystrix:
    enabled: true
  client:
    config:
      fakeUserClient:
        url: https://jsonplaceholder.typicode.com/
        connectTimeout: 5000
        readTimeout: 5000

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          # See https://github.com/spring-cloud/spring-cloud-netflix/issues/1330
          # thread:
          #   timeoutInMilliseconds: 10000
  shareSecurityContext: true

springdoc:
  swagger-ui:
    disable-swagger-default-url=true:
  api-docs:
    path: /api-docs
